version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"    # Maps port 80 in the container to port 8080 on the host
      - "5000:5000"  # Maps port 5000 in the container to port 5000 on the host
    environment:
      FLASK_ENV: development
