apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-attendance-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-attendance-backend
  template:
    metadata:
      labels:
        app: e-attendance-backend
    spec:
      containers:
      - name: e-attendance-backend
        image: 221082168090.dkr.ecr.eu-north-1.amazonaws.com/e-attendance-backend:latest
        ports:
        - containerPort: 8080  # Exposing container port 8080 for backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-attendance-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-attendance-frontend
  template:
    metadata:
      labels:
        app: e-attendance-frontend
    spec:
      containers:
      - name: e-attendance-frontend
        image: 221082168090.dkr.ecr.eu-north-1.amazonaws.com/e-attendance-frontend:latest
        ports:
        - containerPort: 80  # Exposing container port 80 for frontend

---
apiVersion: v1
kind: Service
metadata:
  name: e-attendance-backend-service
spec:
  selector:
    app: e-attendance-backend
  ports:
    - protocol: TCP
      port: 80               # Port exposed on the service for backend
      targetPort: 8080       # Port on the backend container
  type: LoadBalancer          # LoadBalancer type service for backend

---
apiVersion: v1
kind: Service
metadata:
  name: e-attendance-frontend-service
spec:
  selector:
    app: e-attendance-frontend
  ports:
    - protocol: TCP
      port: 80               # Port exposed on the service for frontend
      targetPort: 80         # Port on the frontend container
  type: LoadBalancer          # LoadBalancer type service for frontend
